# Generated by Django 2.2 on 2019-04-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20190411_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
