# Generated by Django 2.2 on 2019-04-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20190411_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.TextField(default='https://www.cricbuzz.com/a/img/v1/595x396/i1/c167814/who-will-edge-the-wankhede-bat.jpg'),
            preserve_default=False,
        ),
    ]
